### PR TITLE
Add "Login as customer" button description for the Customer Profile page 

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request adds the "Login as customer" button description to the Customer Profile page, for Magento version 2.4

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/customers/customer-account-update.html

### CODE REVIEW

**Review by dobooth — CHANGES_REQUESTED** [review]
If the original image is no longer in use, it should be deleted in this PR as well.

**Comment by ZhovnirMaria** [comment]
Hi @dobooth!
Done. Thank you!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1147`.

**Pull request merged**
