### PR TITLE
763 Removed Quote from the link url

### PR DESCRIPTION
**Pull request by makspundyk**
## Purpose of this pull request

This pull request (PR) fix the European Commission link URL on the Value Added Tax (VAT) page.

## Issue Resolved

https://github.com/magento/merchdocs/issues/763

## Magento release version

- [x] 2.4.x

## Affected documentation pages

- https://docs.magento.com/user-guide/tax/vat.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
@makspundyk This is really an error in current docs -- any way that you and put PR to master and then the 2.4.1 and 2.4.2 branches will inherit the fix?

**Comment by leslietilling** [comment]
running tests

**Comment by makspundyk** [comment]
@leslietilling Yes, if we put PR to master and then the 2.4.1 and 2.4.2 - branches will inherit the fix

**Pull request merged**
