### PR TITLE
Update dynamic-blocks-price-rules.md

### PR DESCRIPTION
**Pull request by hellotaran**
## Purpose of this pull request

This pull request (PR) is to provide more details on the association between dynamic block and a promotion rule. Earlier is was not clear. It specifies now what it actually does to the block and to the rule.

## Affected documentation pages

https://docs.magento.com/m2/ee/user_guide/cms/dynamic-blocks-price-rules.html

## Affected Magento editions

- [x] Commerce

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Pull request merged**
