### PR TITLE
Describe how to allow company registration from the storefront

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request describes how to enable company registration from the storefront

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- yes

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/customers/account-company-create.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=create%20company

### CODE REVIEW

**Comment by leslietilling** [comment]
@ZhovnirMaria  Let me know if you want to change PR according to feedback or close it.

**Comment by ZhovnirMaria** [comment]
Hi, @leslietilling 😊 I have updated the PR, please check, thanks)

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@leslietilling the Pull Request is successfully imported.

**Pull request merged**
