### PR TITLE
magento/merchdocs#1166: Sales | Removed deleted "Shipment Workflow" topic from TOC

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

Fix pull request fixes https://github.com/magento/merchdocs/issues/1166

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

### CODE REVIEW

**Comment by dobooth** [comment]
Couple points: 1) This PR doesn't cover what is described in the Issue. 2) The topic only shows how to add a column to a grid, which is covered in https://docs.magento.com/user-guide/stores/admin-grid-layout.html. I don't think we need a new topic to cover adding a column.

**Comment by EvheniiaKolkhiieva** [comment]
@dobooth thank you for the review!

Then in order to avoid confusion for the customers, let's remove the label from the side menu? the specified link does not exist for Magento version 2.4.2

How do you think?
image
image

**Comment by dobooth** [comment]
That is a TOC entry for a bunch of files that we removed last year. Looks like we missed that one. We can remove that from the TOC. If you look in `/src/shipping/delivery.md` you can see all the redirects we have set for those files. Good eye.

**Comment by EvheniiaKolkhiieva** [comment]
@dobooth thank you for clarification!

I have updated this PR:
- remove created "Shipping Workflow" topic
- remove image
- remove the "label: Shipment Workflow+url" from TOC
- remove link from /src/shipping/delivery.md

You can check this.

**Comment by leslietilling** [comment]
Yes, good eye @EvheniiaKolkhiieva -- when we removed Magento Shipping docs that topic was removed, but seems to have snuck back into the TOC.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by sidolov** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1176`.

**Pull request merged**
