### PR TITLE
CAPTCHA checkout storefront

### PR DESCRIPTION
**Pull request by ccondra**
## Purpose of this pull request

This pull request (PR) is to update the Customer Configuration CAPTCHA with the new Forms option to display CAPTCHA during checkout. Added screenshot during checkout; updated config screenshot; and changed heading from "Customer CAPTCHA" to "Storefront CAPTCHA"; removed "EE Only" tag because CAPTCHA is available for all editions.
 
## Magento release version

- [x] 2.4.1

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- [CAPTCHA](https://docs.magento.com/user-guide/stores/security-captcha.html)
- [Customer Configuration](https://docs.magento.com/user-guide/configuration/customers/customer-configuration.html)

## Additional information

Staging: #539

whatsnew
Customer Configuration - CAPTCHA has a new option under Forms that displays CAPTCHA in the storefront during checkout for registered customers.

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]
This looks good to me but I would like @keharper to also review before merge

**Comment by leslietilling** [comment]
@ccondra  Let's include a "what's new" on this one and make sure to squash when merging.

**Comment by ccondra** [comment]
running tests

**Review by keharper — APPROVED** [review]
Approved.

I noticed that you removed an `ee-only` tag but left the images in the `images-ee` directory. Not a big deal, but maybe something to be addressed in another PR.

**Comment by ccondra** [comment]
Re: the question about the image being in the ee directory, it's OK as is. We used to publish  a different image for each edition in cases where the options were different. Now the user guide is for all editions, but with the default edition ee. As all screenshots, this one was captured with ee and includes some elements that are ee-only. So that's why the image belongs in the images-ee.  However, CAPTCHA is not limited to ee.

**Pull request merged**
