### PR TITLE
The relationship between products and categories

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/merchdocs/issues/1342

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/catalog/categories.html

### CODE REVIEW

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
Verified via REST that if you create a product without specifying a category, Magento doesn't assign a default category. The changes are correct.

**Comment by keharper** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import code to magento-merchdocs

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@keharper the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1346`.

**Pull request merged**
