### PR TITLE
Added additional information to product reviews page. [Cloned from /1665]

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
## Purpose of this pull request

Added additional information to product reviews page. 
Cloned from https://github.com/magento/merchdocs/pull/1665 with re-forked repo, to avoid an errors during import.

### CODE REVIEW

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Pull request merged**
