### PR TITLE
Update columns for the Credit Memos page

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request updates columns for the Credit Memos page

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

https://docs.magento.com/user-guide/sales/credit-memo-print.html
https://docs.magento.com/user-guide/sales/credit-memos.html

### CODE REVIEW

**Comment by ZhovnirMaria** [comment]
Hi, @leslietilling 
My test has failed and the error seems to be not on my end. Could you help me? Thank you ☺️

**Comment by dobooth** [comment]
Yes, it is on our end.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/merchdocs` repository. Branch name: `imported-ZhovnirMaria-merchdocs-1653`.

**Pull request merged**
