### PR TITLE
Added additional info about widgets managing

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
## Purpose of this pull request

Added additional minor info about widget managing (how to edit and delete widgets)

This pull request (PR) ...

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ...

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ...

## Affected documentation pages

https://docs.magento.com/user-guide/cms/widget-create.html
- ...
- ...

whatsnew
Expanded [Creating and Managing Widgets](https://docs.magento.com/user-guide/cms/widget-create.html) topic to include widget edit and delete information.

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]
Committed changes to update topic title and structure to reflect the addition of the edit and delete functionality.

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@leslietilling the pull request successfully imported.

**Pull request merged**
