### PR TITLE
Magento instead of Magneto

### PR DESCRIPTION
**Pull request by df2k2**
## Purpose of this pull request

This pull request (PR) ...

## Affected documentation pages

- ...
- ...

## Affected Magento editions

- [ ] Open Source
- [ ] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
Thank you for taking the time to submit a contribution PR! It is required that you submit a signed CLA before we can process your contribution.

Click the "Details" link in the review requirements section and complete the CLA. Then add a comment letting us know it is completed. We will review your submission and let you know if we have any questions or revisions.

**Comment by hickskenh** [comment]
@df2k2 - Thank you for your submission.  That one is such a slip of the hand for us X-men fans. @leslietilling has approved your PR but Adobe requires a signed CLA before we can merge any PR. 

Click the "Details" link in the review requirements section and complete the CLA. Then add a comment letting us know it is completed. We will review your submission and let you know if we have any questions or revisions.

We will be out for the holidays from Dec. 23 through Jan 1. If we haven't heard from by when we're back in office, we'll close your PR, and you will lose your submission points.

**Comment by df2k2** [comment]
> 
> 
> @df2k2 - Thank you for your submission. That one is such a slip of the hand for us X-men fans. @leslietilling has approved your PR but Adobe requires a signed CLA before we can merge any PR.
> 
> Click the "Details" link in the review requirements section and complete the CLA. Then add a comment letting us know it is completed. We will review your submission and let you know if we have any questions or revisions.
> 
> We will be out for the holidays from Dec. 23 through Jan 1. If we haven't heard from by when we're back in office, we'll close your PR, and you will lose your submission points.

Signed.  Thanks for pointing that out!! :)

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
@df2k2 - Thanks.  I've tested and merged your PR.  Keep the corrections and updates coming.

**Pull request merged**
