### PR TITLE
Updated Currency-Configuration.md

### PR DESCRIPTION
**Pull request by GDauer**
## Purpose of this pull request

Minor change to the **Currency Configuration** documentation page.
The purpose of this **PR** is because it's kinda take me a couple minutes to understand that this section only appears in the default configuration view. And it's not something that's missing or wrong in the documentation.

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/stores/currency-configuration.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
I'm not sure what you mean by "Default config" here. I think we might need to add some additional clarity here. Can you provide some more specifics around this?

**Comment by GDauer** [comment]
> I'm not sure what you mean by "Default config" here. I think we might need to add some additional clarity here. Can you provide some more specifics around this?

Yep, just changed It, think it's better now?

**Comment by leslietilling** [comment]
running tests

**Pull request merged**
