### PR TITLE
Add save_rewrites_history description

### PR DESCRIPTION
**Pull request by mischabraam**
## Purpose of this pull request

This pull request (PR) adds a description of the optional column `save_rewrites_history` for product import.

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/system/data-attributes-product.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [ ] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
Thank you for taking the time to submit a contribution PR! It is required that you submit a signed CLA before we can process your contribution.

Click the "Details" link in the review requirements section and complete the CLA. Then add a comment letting us know it is completed. We will review your submission and let you know if we have any questions or revisions.

**Comment by hickskenh** [comment]
Hey @mischabraam.  It has been a few weeks since we asked you to review and sign the Adobe CLA.  Without a signed CLA, we are unable to process or merge your updates.  Let us know if you have any questions.

**Comment by hickskenh** [comment]
closing due to inactivity/no CLA

**Pull request closed without merging**
