### PR TITLE
Update Test Credit Card Link Payfort

### PR DESCRIPTION
**Pull request by niravkrish**
## Purpose of this pull request

The paypal test card details link provided in the document is longer exist so I have changed it to new one. so any one can find out test card details easily from devdocs itself.

I have replaced
https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm
Link with below link
https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/payment/paypal-payflow-pro.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [ ] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
Hey @niravkrish. I looked at the link you changed, both links work for me, and while the us/gb is different in the link, i do not see any content difference on the pages. Can you help me understand why you want to make this change?

**Comment by niravkrish** [comment]
The link was not worked for me.

It was going to the not found page that's why i was created a Pull request for that.

Today it is working.

**Pull request closed without merging**
