### PR TITLE
Update data-attributes-product.md

### PR DESCRIPTION
**Pull request by Sv0gls**
## Purpose of this pull request

Added the **related_position**, **crosssell_position**, **upsell_position** fields that set the position (sort order) or Related, Cross-sell and Up-sell Products.

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/system/data-attributes-product.html

## Affected Magento editions

- [X] Open Source
- [X] Commerce
- [ ] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
Thank you for taking the time to submit a contribution PR! It is required that you submit a signed CLA before we can process your contribution. 

Click the "Details" link in the review requirements section and complete the CLA. Then add a comment letting us know it is completed. We will review your submission and let you know if we have any questions or revisions.

**Comment by Sv0gls** [comment]
CLA is signed.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
