### PR TITLE
Update engage.md

### PR DESCRIPTION
**Pull request by domaniEquestrian**
Add plural to market.

## Purpose of this pull request

This pull request (PR) makes market plural, which is more correct given the sentence.

## Affected documentation pages

- https://docs.magento.com/user-guide/quick-tour/engage.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by domaniEquestrian** [comment]
Hi @leslietilling ; Could it be that we didn't get any points for these contributions? :) If yes, could you let me know why not please? With kind regards

**Comment by leslietilling** [comment]
> Hi @leslietilling ; Could it be that we didn't get any points for these contributions? :) If yes, could you let me know why not please? With kind regards

Hi @domaniEquestrian For the specifics about how points are awarded based on the type of change submitted, please refer to https://devdocs.magento.com/contributor-guide/contributing.html#docs-awards-and-points.

You had multiple Editorial PRs with very small changes that had to be combined for merge to master. Our policy is that these types of fixes should be combined into a single PR. We know you are a first time contributor, so we allowed the system to assign 1 point (Editorial) to each.

In the thread for the first PR (https://github.com/magento/merchdocs/pull/639), @BrentRobert requested the Partner:PHPro label so that it reflects for the team and I let him know that we would apply that to the one PR since they should have been combined.

Please let me know if this does not make sense or if you have any other questions.

**Comment by domaniEquestrian** [comment]
Okay, yes I am very sorry for the hassle and doing it wrong! Does my PHPro label now applies for all the requests I do in the future or do I still need to fix something in order to have this applied automatically?

Kind regards
Verzonden vanaf mijn Samsung Galaxy-smartphone.



-------- Oorspronkelijk bericht --------
Van: Leslie Tilling <notifications@github.com>
Datum: 13/08/2020 16:11 (GMT+01:00)
Aan: magento/merchdocs <merchdocs@noreply.github.com>
Cc: domaniEquestrian <info@domani-equestrian.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [magento/merchdocs] Update engage.md (#642)


Hi @leslietilling<https://github.com/leslietilling> ; Could it be that we didn't get any points for these contributions? :) If yes, could you let me know why not please? With kind regards

Hi @domaniEquestrian<https://github.com/domaniEquestrian> For the specifics about how points are awarded based on the type of change submitted, please refer to https://devdocs.magento.com/contributor-guide/contributing.html#docs-awards-and-points.

You had multiple Editorial PRs with very small changes that had to be combined for merge to master. Our policy is that these types of fixes should be combined into a single PR. We know you are a first time contributor, so we allowed the system to assign 1 point (Editorial) to each.

In the thread for the first PR (#639<https://github.com/magento/merchdocs/pull/639>), @BrentRobert<https://github.com/BrentRobert> requested the Partner:PHPro label so that it reflects for the team and I let him know that we would apply that to the one PR since they should have been combined.

Please let me know if this does not make sense or if you have any other questions.

**Comment by BrentRobert** [comment]
Hi @domaniEquestrian, you're currently not linked to our team.
The Magento Dashboard does say you're invited and I can't send another invitation. 

Your account needs to be in the Github theme before the labels are applied AND the points count.

**Pull request merged**
