### PR TITLE
Update shipping-label-workflow.md. minor issue

### PR DESCRIPTION
**Pull request by denish-c-vachhani**
Added space after Dot(.)

## Purpose of this pull request

This pull request (PR) Minor typo issue. added space after Dot(.)

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/shipping/shipping-label-workflow.html

## Affected Magento editions

- [ ] Open Source
- [x] Commerce
- [ ] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
@denish-c-vachhani Thank you for correcting some of our errors.  In the future when you have several small changes like these, please work them and submit a single PR for the changes.  Also, once a reviewer has reviewed a PR, please don't work in the PR unless you are changes are requested or questions are asked.

**Comment by hickskenh** [comment]
running tests

**Comment by denish-c-vachhani** [comment]
@hickskenh, Thanks for your suggestions. As i am reading docs and some of the points i have directly edit from link provided in document above "Edit this page on GitHub"can be cause the different branch for small changes.

**Pull request merged**
