### PR TITLE
Update search-engine-robots.md

### PR DESCRIPTION
**Pull request by sebfie**
Display default value as defined in Magento_Theme module : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/etc/config.xml#L24

## Purpose of this pull request

Display on documentation the right value of Default robots.txt

This pull request (PR) ...

## Magento release version

2.4

## Affected documentation pages

https://docs.magento.com/user-guide/marketing/search-engine-robots.html

### CODE REVIEW

**Comment by dobooth** [comment]
Hi @sebfie and thanks for the contribution. Can you please sign the Adobe CLA below so that we may process this PR?

**Comment by sebfie** [comment]
Sure ! I did it !

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
