### PR TITLE
changes categories to products to access to edit products

### PR DESCRIPTION
**Pull request by MPur**
It seems to be "Products" instead of "Categories" in this section for the admin sidebar path.

## Purpose of this pull request
Improve documentation

This pull request (PR) ...

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
@MPur  Thank you for your contribution. I've reviewed and approved your PR, but it cannot be merged until you sign the Adobe CLA. If you're not aware, we recently opened merchdocs for public submissions and have implemented some new processes and procedures to help establish and maintain consistency. This process is new for us also. It is a simple but important change, and we thank you for taking the time to submit the correction.

**Comment by hickskenh** [comment]
@MPur We appreciate your contribution. But we are legally restricted from merging a PR that doesn't have a signed CLA for the user.  If we don't hear back from you before Monday, 11/25, we'll have to close your PR, and you will lose your submission points. See the CLA Details link.

**Comment by hickskenh** [comment]
closed due to lack of response.

**Pull request closed without merging**
