### PR TITLE
Update product-translate.md

### PR DESCRIPTION
**Pull request by denish-c-vachhani**
General Information tab refers to Magento 1.

## Purpose of this pull request

This pull request (PR) General Information tab refers to Magento 1, changed content as per magento 2.

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/catalog/product-translate.html
- https://docs.magento.com/m2/ee/user_guide/catalog/product-translate.html
- https://docs.magento.com/m2/b2b/user_guide/catalog/product-translate.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

## Additional information

image

image
Magento 1 General Information tab, Image reference - https://docs.magento.com/m1/ee/user_guide/catalog/category-general-information.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
@denish-c-vachhani    Hey.  This file failed testing due to a linting rule error.  I tried to edit the file myself, but i don't have permissions to your fork.  See the linting rule text, update the file and commit your change so can run tests again.  Thanks.

MD009 - Trailing spaces
Tags: whitespace

Aliases: no-trailing-spaces

Parameters: br_spaces (number; default: 0)

This rule is triggered on any lines that end with whitespace. To fix this, find the line that is triggered and remove any trailing spaces from the end.

The br_spaces parameter allows an exception to this rule for a specific amount of trailing spaces used to insert an explicit line break/br element. For example, set br_spaces to 2 to allow exactly 2 spaces at the end of a line.

Note: you have to set br_spaces to 2 or higher for this exception to take effect - you can't insert a br element with just a single trailing space, so if you set br_spaces to 1, the exception will be disabled, just as if it was set to the default of 0.

**Comment by denish-c-vachhani** [comment]
@hickskenh, i have checked and removed extra space.

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
