### PR TITLE
Tier prices - Add note to clarify discount calculation

### PR DESCRIPTION
**Pull request by ihor-sviziev**
## Purpose of this pull request

This pull request (PR) adds clarification that tier prices are calculated on top of "Price" field and not using "Special price".

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/catalog/product-price-tier.html
- https://docs.magento.com/m2/ee/user_guide/catalog/product-price-tier.html
- https://docs.magento.com/m2/b2b/user_guide/catalog/product-price-tier.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

## Links to Magento source code or PRs

- https://github.com/magento/magento2/issues/26583

## Additional information

We had discussion with @nazar65 about fixing the issue https://github.com/magento/magento2/issues/26583
There were two options:
1. Fix the calculated percentage on the product page on top of existing behavior in the admin + document it <-- that's why I created this PR

2. Change calculation of tier prices to be working with special prices.

During discussion we found that 2nd option will affect too many magento installations that working with tier prices, so decided to go with 1st option.

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
Hey @ihor-sviziev. Thank you for submitting the clarification.  I'd like to take your information and adjust it slightly.  I'd like to move the note to the end of step 2, where the user is defining the percent.  I'd like to reword step 2.   would you agree with this change?

2. In the next field, enter the discounted price as a percentage off the base price of the product. For example, for a 15 percent discount, enter the number 15. (The price is saved with two decimal positions, such as “15.00”.) 
**Note**: To get the discount price, the defined percentage is calculated against the value defined in the **Price** field, not the **Special Price** field.

**Comment by ihor-sviziev** [comment]
@hickskenh sure, I don't mind

**Comment by hickskenh** [comment]
@ihor-sviziev Thanks for the speedy reply.  i should be able to run tests and get this live today.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
