### PR TITLE
Issue with the description line in Maximum Qty Allowed in Shopping Cart

### PR DESCRIPTION
**Pull request by dharatuvar**
## Purpose of this pull request

There is no setting to set the maximum quantity by customer group. So, there should not be any mention to set the quantity by customer group. It would be the overall quantity per order for any customer group as of now.

### CODE REVIEW

**Comment by leslietilling** [comment]
@sidolov  Can you please confirm that this is correct?

**Comment by dobooth** [comment]
@sidolov

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@leslietilling , @dobooth I can confirm the correct behavior described in the PR.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
running tests

**Pull request merged**
