### PR TITLE
Add documentation about new system config option - Enable Inventory Check On Cart Load

### PR DESCRIPTION
**Pull request by adifucan**
## Purpose of this pull request

This pull request (PR) introduces documentation about new system config option - Enable Inventory Check On Cart Load

## Magento release version

- [x] 2.4.4

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages
- merchdocs/src/configuration/catalog/inventory.md
- merchdocs/src/catalog/inventory-options-global.md

## Links to Magento source code or PRs
- https://github.com/magento-commerce/magento2ce/pull/7021

whatsnew
Descriptions added for the _Enable Inventory Check On Cart Load_ configuration setting in the [Configure Global Options](https://docs.magento.com/user-guide/catalog/inventory-options-global.html) and [Inventory configuration reference](https://docs.magento.com/user-guide/configuration/catalog/inventory.html#stock-options) topics.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dshevtsov, an error occurred during the Pull Request import.

**Comment by dshevtsov** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dshevtsov the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1456`.

**Comment by keharper** [comment]
@adifucan I skimmed your code PR and I see that you run tests against the GraphQL code. Do we need to add some sort of note to the `placeOrder` mutation to say how this new config option can affect performance? Or maybe add a new error to the list?

https://devdocs.magento.com/guides/v2.4/graphql/mutations/place-order.html

The same applies to `setPaymentMethodAndPlaceOrder`. It's currently listed as deprecated, but I think the Honey Badgers are planning to undeprecate it.

**Comment by adifucan** [comment]
@keharper Yes, I covered these changes with web api graphQL tests. But you do not think that we need to add a new error to the list.
We definitely need to add documentation about performance impact. But it will be done in scope of other task. This new config setting is part of large Performance Pack epic. We will provide detailed documentation about all checkout performance improvements (this new config setting is one of them) later.

**Pull request merged**
