### PR TITLE
magento/merchdocs#1157: Add gift card account history

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request (PR) describes the "History" section of the gift card account page.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/product-gift-card-accounts.html

whatsnew
Added the [Gift card account history](https://docs.magento.com/user-guide/catalog/product-gift-card-accounts.html) section to the Gift Cards topic.

### CODE REVIEW

**Comment by dobooth** [comment]
There is no need to open an issue for a PR you are already creating.

**Comment by ZhovnirMaria** [comment]
@dobooth 
Thanks, next time I will try not to create an issue.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1158`.

**Pull request merged**
