### PR TITLE
Update the Purchase Order field for the Company Credits pages

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request updates the Purchase Order field for the Company Credits pages

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/customers/credit-company-activity.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Company%20Credit%20Activity
https://docs.magento.com/user-guide/customers/credit-company-reimburse.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=Receiving%20Payments

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]
Thanks for catching this!  Looks like we missed it as part of B2B-473.

**Comment by leslietilling** [comment]
@ZhovnirMaria  I will let you resolve the conflicts and then I can import this for merge.

**Comment by ZhovnirMaria** [comment]
@leslietilling, Thank you! Done✅

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@leslietilling the pull request successfully imported.

**Pull request merged**
