### PR TITLE
magento/merchdocs#1171: Moderation of product reviews

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request adds a block about moderation of product reviews to the Product Reviews page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/settings-advanced-product-reviews.html

## Additional information

Screenshot 2021-04-13 at 15 26 50

### CODE REVIEW

**Comment by dobooth** [comment]
Please remove the image you are replacing if it is not used in another topic.

**Comment by ZhovnirMaria** [comment]
@dobooth 
Thanks, done!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1172`.

**Pull request merged**
