### PR TITLE
Fixed a minor grammatical error

### PR DESCRIPTION
**Pull request by indraneilk**
Added "by" to fix a minor grammatical error in the sentence "The selection varies attribute set, and you can complete them later."

## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) fixes a minor grammatical error in the merchant documentation for creating a simple product.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

2.4, 2.3

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- ... No, to both.

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- ... No, it's an update to the simple product creation documentation for merchants.

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- ... https://docs.magento.com/user-guide/v2.3/catalog/product-create-simple.html
- ... https://docs.magento.com/user-guide/catalog/product-create-simple.html

## Links to Magento source code or PRs

_OPTIONAL. If this pull request references a file in a Magento codebase repository or a code PR, add it here._

- ...
- ...

## Additional information

_OPTIONAL. What other information can you provide?_
It's a minor grammatical fix.

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
Good eye and thanks, @indraneilk.

**Comment by dobooth** [comment]
@indraneilk Please sign the Adobe CLA so that we may proceed with this PR.

**Comment by indraneilk** [comment]
@dobooth Awesome, I've signed it now.

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
