### PR TITLE
Issue #1005 Correcting the Full Path value of the default theme logo

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

This pull request (PR) fixes https://github.com/magento/merchdocs/issues/1005

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/design/logo-upload.html

## Links to Magento source code or PRs

- https://github.com/magento/magento2/blob/2.3/app/design/frontend/Magento/blank/web/images/logo.svg

### CODE REVIEW

**Review by danidelcar — APPROVED** [review]

**Comment by EvheniiaKolkhiieva** [comment]
@danidelcar , thank you for reviewing and approving! 😊

**Comment by danidelcar** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by danidelcar** [comment]
> @danidelcar , thank you for reviewing and approving! 😊

no problem @EvheniiaKolkhiieva !

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by lenaorobei** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@lenaorobei the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1285`.

**Pull request merged**
