### PR TITLE
magento/merchdocs#729 2FA configuration docs

### PR DESCRIPTION
**Pull request by vkranjith**
- Replaced the 2FA configuration image with the latest one

## Purpose of this pull request

This pull request (PR)  is to update one of the screenshots for the 2FA feature in 2.4.x to avoid confusion.

## Magento release version

- [x]  2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/stores/security-two-factor-authentication.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
@vkranjith  This looks like it corrects the current 2.4 docs, so you can submit this PR to master. If we merge to 2.4.1-develop, this fix won't go to production until October.

**Comment by vkranjith** [comment]
Sure @leslietilling.

**Comment by vkranjith** [comment]
@leslietilling - I have created another pull request to master branch.
https://github.com/magento/merchdocs/pull/735

**Comment by leslietilling** [comment]
@vkranjith Go ahead and close this one.

**Pull request closed without merging**
