### PR TITLE
remove empty line

### PR DESCRIPTION
**Pull request by bjoern-flagbit**
on ee the table is broken because of too many lines

see:
https://docs.magento.com/m2/ee/user_guide/catalog/product-types.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
@bjoern-flagbit  Hello and thank you for taking the time to submit the correction. We really appreciate updates and fixes from the Community! 

Please sign the Adobe CLA. This is a requirement and when this is done, we can process this PR quickly.

**Comment by bjoern-flagbit** [comment]
Done

**Comment by bjoern-flagbit** [comment]
looks fine now thx 👍

**Pull request merged**
