### PR TITLE
Add new SMTP Mail configuration

### PR DESCRIPTION
**Pull request by barryvdh**
## Purpose of this pull request

Adds documentation for the new configuration options (when merged) from this PR: https://github.com/magento/magento2/pull/32241

## Magento release version

2.4-develop

## Product editions

Magento Open Source +Adobe Commerce only?

## Affected documentation pages

- https://docs.magento.com/user-guide/configuration/advanced/system.html

## Links to Magento source code or PRs

- https://github.com/magento/magento2/pull/32241

## Additional information

Merge after a new release containing the mentioned PR.

### CODE REVIEW

**Comment by leslietilling** [comment]
@barryvdh  Is this for the 2.4.5 release?

**Comment by leslietilling** [comment]
I am marking as "on hold" until we know which release will include this update. Then we can make sure to merge to the correct develop branch for doc updates.

**Comment by barryvdh** [comment]
The Pull Request is merged. Not sure which version it will be released in though.

**Comment by leslietilling** [comment]
> The Pull Request is merged. Not sure which version it will be released in though.

Looks like 2.4.6. We don't yet have a development branch for that, but will have one soon.

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@leslietilling the Pull Request is successfully imported.

**Review by leslietilling — APPROVED** [review]

**Comment by dobooth** [comment]
Merged on internal repo.

**Pull request closed without merging**
