### PR TITLE
MC-40589: Document page builder preview limitation for filtering/sorting configurable, grouped and bundle products by price

### PR DESCRIPTION
**Pull request by bubasuma**
## Purpose of this pull request

This pull request (PR) adds a warning information about page builder preview limitation for filtering/sorting configurable, grouped and bundle products by price.

## Magento release version

- [x] 2.4.x

- [ ] 2.3.x

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [x] Other feature set, please specify: Page Builder extension

## Affected documentation pages

- https://docs.magento.com/user-guide/cms/page-builder-add-content-products.html

whatsnew
Updated [Add Content - Products](https://docs.magento.com/user-guide/cms/page-builder-add-content-products.html) to add warning information about Page Builder preview limitation for filtering/sorting configurable, grouped, and bundle products by price.

### CODE REVIEW

**Comment by bubasuma** [comment]
I will update this pull request after master branch will be synced with 2.4.3-develop. see https://github.com/magento/merchdocs/pull/1050

**Comment by leslietilling** [comment]
I did a manual run of the synch job between the master and 2.4.3-develop branches and changes still don't seem to be showing up.

**Comment by bubasuma** [comment]
@leslietilling I just fixed it. thanks

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
running tests

**Pull request merged**
