### PR TITLE
Markdown linting: MD030

### PR DESCRIPTION
**Pull request by leslietilling**
## Purpose of this pull request

This pull request (PR) addresses #342 

To address MD030:
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md030---spaces-after-list-markers

**NOTE:** MerchDocs is using **one space** between the marker and the text. This is a more natural implementation and matches the Adobe docs syntax guidelines.

Also did some editing for other style consistencies as long as I was in there.

## Affected documentation pages

Too many to list

### CODE REVIEW

**Comment by leslietilling** [comment]
I grappled with this one. Using 1 is least disruptive and more common, where 2 would require changes to the vast majority of content files. The idea of then having to change them back later as we try to integrate with SCCM for helpx/ExL on the Adobe side is something I'd rather avoid. The only other option would be that we simply don't implement md030 in this repo and it allows for either.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
This test run is intended for CI/CD testing.

**Comment by leslietilling** [comment]
Let's hold on merging this one just yet. I will discuss with writers to decide if we will implement this rule or not.

**Comment by leslietilling** [comment]
Discussed in Merchdocs meeting (7/8/2020). If it was possible to use as one or two being valid as long as consistent, that was first choice. Sadly, it does not work that way. So second choice is to implement as one space according to Adobe syntax standard.

**Comment by dshevtsov** [comment]
We should start a discussion about Adobe style preference in all documentation projects then.
cc @jeff-matthews

**Comment by jeff-matthews** [comment]
Agreed @dshevtsov. However, I don't think it's the best use of time to change rules we've already implemented just so they match Adobe's syntax. Not unless those changes can be done more quickly and efficiently (e.g., programatically) than the process of original implementation. We have much higher priorities.

**Comment by dshevtsov** [comment]
@jeff-matthews I agree. But we should add and keep it in our backlog to avoid growth of inconsistency (and thus, future concerns from writers and contributors) between projects.

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
We are in compliance with most things already, but there will be some changes to make to be compatible with Adobe authoring: https://docs.adobe.com/content/help/en/collaborative-doc-instructions/collaboration-guide/markdown/syntax-style-guide.html

Right now I don't want to make major changes that will put us farther away from this standard.

**Comment by jeff-matthews** [comment]
@dshevtsov, you're right. For future, new doc projects we should align with Adobe standards to make migration to Adobe publishing infrastructure easier (if required in the future). For devdocs, I think we've already implemented all the rules we plan to implement with the exception of code blocks. I think the same is true for the omsdocs project.

This also raises larger questions about the type of markdown we use. We should try our best to use either Adobe-flavored MD or GitHub-flavored MD for new projects as well and avoid non-standard, idiosyncratic MD and Jekyll tags.

**Pull request merged**
