### PR TITLE
ACP2E-424: [Documentation] Mention that product will have the same Allow permission in scope of all assigned categories in the Catalog

### PR DESCRIPTION
**Pull request by vkolesny**
## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) is to mention that product will have the same Allow permission in scope of all assigned categories in the Catalog.
It was clarified in scope of ACP2E-416 and should be added to the Documentation.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

Magento 2.4.x

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

Adobe Commerce only

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

No

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

https://docs.magento.com/user-guide/catalog/category-permissions.html

### CODE REVIEW

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/merchdocs` repository. Branch name: `imported-magento-l3-merchdocs-1654`.

**Comment by vkolesny** [comment]
Converted to draft to add 1 similar callout regarding Root Category Allow permissions inheritance.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the branch with the code is successfully imported into the `magento-devdocs/merchdocs` repository. Branch name: `imported-magento-l3-merchdocs-1654`.

**Pull request merged**
