### PR TITLE
Hidden tax document

### PR DESCRIPTION
**Pull request by vkolesny**
## Purpose of this pull request

This pull request (PR) adds new page to help customers understand hidden tax calculation. 

If Magento Commerce, please specify:

- [ ] Commerce only?
- [ ] Commerce with B2B?

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
ran locally and everything passed. Will try again

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Comment by shrielenee** [comment]
@vkolesny Include the topic link in your PR template if possible! Thanks!

**Comment by vkolesny** [comment]
Hi @shrielenee,

Done.

**Pull request merged**
