### PR TITLE
Providing more detailed information for transactions grid, data, details, and Childs

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

This pull request (PR) is a duplicate of the https://github.com/magento/merchdocs/pull/1198 PR, with all suggested edits

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/sales/transactions.html

whatsnew
Updated [Transactions](https://docs.magento.com/user-guide/sales/transactions.html) to include information about viewing transaction details.

### CODE REVIEW

**Comment by EvheniiaKolkhiieva** [comment]
Hi @dobooth and @leslietilling, I have created this PR which is a duplicate of the https://github.com/magento/merchdocs/pull/1198 .

This pull request includes all your suggested edits and additions, please check. 

Thank you!

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@leslietilling the pull request successfully imported.

**Pull request merged**
