### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by domaniEquestrian**
Missing dash in business-to-consumer commerce.

## Purpose of this pull request

This pull request (PR) fixes a missing dash in business-to-consumer commerce.

## Affected documentation pages

- https://docs.magento.com/user-guide/getting-started.html

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
Hello @domaniEquestrian. Thank you for submitting your edits in our guide! Opening many small edit PRs can overload our testing system, so I will be merging them into a single `small-changes` branch and then open a new PR for test/merge to our master for publication.

In the case where you already have a small change open PR, you can add to it by selecting the same branch as the open PR. The GitHub UI default creates a new one, such as `domaniEquestrian:patch-2` or `domaniEquestrian:patch-3`, but you can change it to the existing branch of your open PR.

**Comment by BrentRobert** [comment]
Hi @leslietilling does this PR count as a partner contribution? As the labels do not apply on this repository?

**Comment by leslietilling** [comment]
> Hi @leslietilling does this PR count as a partner contribution? As the labels do not apply on this repository?

@BrentRobert  Yes, partner labels do apply here, but the submitter does not appear to be a member of a partner team and doesn't look like they have opened any previous Magento PRs, so the automation did not pick that up. Is this a partner account? We do expect partners to follow similar rules as Magento and Devdocs so that extra points aren't collected by opening many tiny PRs.

**Comment by BrentRobert** [comment]
> > Hi @leslietilling does this PR count as a partner contribution? As the labels do not apply on this repository?
> 
> @BrentRobert Yes, partner labels do apply here, but the submitter does not appear to be a member of a partner team and doesn't look like they have opened any previous Magento PRs, so the automation did not pick that up. Is this a partner account? We do expect partners to follow similar rules as Magento and Devdocs so that extra points aren't collected by opening many tiny PRs.

I agree with the tiny PR's. Those could have been in one. She should be part of my team. Seems something went wrong with the invites.

**Comment by leslietilling** [comment]
@BrentRobert  I will apply the `Partner: PHPro` manually to this PR so that the points are awarded :)

**Comment by domaniEquestrian** [comment]
Hi @leslietilling : sorry I'm quite new to GitHub, so I had no clue how to bind/merge them all together. Will do for the future! Is my account now linked to PHPro for the future? Or do I need to make some adjustments so that the label will be applied automatically in the future?

**Pull request merged**
