### PR TITLE
ISSUE-499 - Update images for data export

### PR DESCRIPTION
**Pull request by AndreyChorniy**
## Purpose of this pull request

This pull request (PR) deleted screenshots for a page with examples of CSV file opened in OpenOffice Calc and Notepad++ 

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/m2/ee/user_guide/system/data-csv.html

## Additional information
Fixes https://github.com/magento/merchdocs/issues/499

### CODE REVIEW

**Comment by shrielenee** [comment]
Hey @AndreyChorniy -- As mentioned in the related issue we should remove the screenshots altogether. They too quickly become outdated and don't show information that is consumable by accessibility standards. They also don't add much to the topic. Is that something you can work on?

**Comment by shrielenee** [comment]
Also, fill out the PR description form completely. This is required for us to process PRs, so that we can quickly ascertain what the changes are and review them efficiently. 🙇‍♀️

**Comment by AndreyChorniy** [comment]
Hello @shrielenee, I have deleted those screenshots. 
Could you please review my PR once again?

**Review by shrielenee — APPROVED** [review]

**Comment by shrielenee** [comment]
I have verified you removed the outdated screenshots. 👍

**Comment by shrielenee** [comment]
running tests

**Pull request merged**
