### PR TITLE
price-rules-cart.md. minor typo issue

### PR DESCRIPTION
**Pull request by denish-c-vachhani**
Removed unwanted special charecter (_) and added blank line between line and image.

## Purpose of this pull request

This pull request (PR) minor typo issue and added blank line between line and image.

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart.html
- https://docs.magento.com/m2/ee/user_guide/marketing/price-rules-cart.html
- https://docs.magento.com/m2/b2b/user_guide/marketing/price-rules-cart.html
## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

## Additional information

image

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
