### PR TITLE
Added additional information to Comparison List page [CLONE OF /pull/1674]

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
## Purpose of this pull request

Added additional information to Comparison List page
Clone of  https://github.com/magento/merchdocs/pull/1674 from re-forked repo to avoid an errors during the import

whatsnew
Updated the [Comparison List](https://docs.magento.com/user-guide/marketing/product-compare.html) topic to include different methods that customers can use to access the comparison list on the storefront.

### CODE REVIEW

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Review by leslietilling — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Pull request merged**
