### PR TITLE
Deleting a "Custom Pricing" topic that duplicates another same topic in the Catalog section

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

There is a detailed description of the topic "Custom Pricing", which is in the "Shared Catalog" block.
There is also a topic that, in fact, does not have much meaning and semantic load, but simply redirects to the topics below in the same section. Therefore, it would be more rational to delete the duplicate.
image

This pull request (PR) removes a "Custom Pricing" topic that duplicates another same topic in the Catalog section

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/catalog/product-price-custom.html
- https://docs.magento.com/user-guide/catalog/catalog-shared-custom-pricing-update.html

### CODE REVIEW

**Review by dobooth — CHANGES_REQUESTED** [review]
- Please combine the two topics as needed. 
- The TOC must to updated re: the deleted file

**Comment by EvheniiaKolkhiieva** [comment]
Hi @dobooth, I have deleted the file from TOC and run rake, could you please approve this PR? 
(there was no need to combine topics since there was not much information on the remote topic)

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
