### PR TITLE
Update catalog-flat.md

### PR DESCRIPTION
**Pull request by hellotaran**
## Purpose of this pull request

This pull request (PR) for Flat catalog - link to KB #69 

## Affected documentation pages

https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html
https://docs.magento.com/m2/ee/user_guide/catalog/catalog-flat.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
Updated link format.  [text](address).   Link command breaks the build.

**Comment by hickskenh** [comment]
Fixes #69 - merging to Master

**Comment by hickskenh** [comment]
@hellotaran Thank you for your contribution. I updated the link format, you don't need the link command when using a web link.  Your contribution has been merged and will be published in the next build.  Thanks again.

**Comment by hellotaran** [comment]
> 
> 
> @hellotaran Thank you for your contribution. I updated the link format, you don't need the link command when using a web link. Your contribution has been merged and will be published in the next build. Thanks again.

Thank you Ken. Where do we get the documentation on formatting? I followed the same we have on the same page. There is a link on 'Cron' text on the same page. Asking just for future purposes.

**Comment by hickskenh** [comment]
@hellotaran  That is a great question.  The cron link in that file links to another file in the project.  If you are linking to an image or other topic in the merchdocs project, you need the "link" command.  If you are linking out to a web address, you don't need the "link" command because the web address is a separate, stand-alone object.  A cheat sheet of commands and formatting may be something we look at posting in the future.  But for now, I suggest doing a keyword search or look around in other topics to find a similar example and mimic the formatting.  For contacting us with questions, check out the **Contact the Magento Docs Team** section on the [Contributing page](https://github.com/magento/merchdocs/blob/master/.github/CONTRIBUTING.md).

**Comment by hickskenh** [comment]
@hellotaran Hey.  i found some formatting info i the wiki.  https://github.com/magento/merchdocs/wiki/Writing-Content#links

**Pull request merged**
