### PR TITLE
Criteria for Reorder functionality added

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
## Purpose of this pull request

This pull request contains additional information on the Reorder page.

I have provided the criteria for reorder functionality to be available for an order. 

**Note:**
All of the criteria are checked against the latest Magento 2.3.4 version and verified.

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/sales/reorders-allow.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

## Links to Magento source code or PRs

- https://github.com/magento/magento2/blob/4b78d9ae323d076642f2d2d0fabc1dee217a9e52/app/code/Magento/Sales/Model/Order.php#L881

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
thank you @ajithkumar-maragathavel for your submission.

**Comment by ajithkumar-maragathavel** [comment]
@hickskenh Thanks for the review.

**Pull request merged**
