### PR TITLE
Add steps for locked locale change

### PR DESCRIPTION
**Pull request by IngusSkaistkalns**
## Add steps for locked locale change

Added documentation steps how to configure new store views locale in case *Locale* select and *Use Website* checkbox are disabled due to `app/etc/config.php` locale configuration block.

If Magento Commerce, please specify:

- [x] Commerce only?
- [ ] Commerce with B2B?

## Affected documentation pages

- https://docs.magento.com/user-guide/stores/store-language-add.html

`master` is the default branch. Merged pull requests to `master` go live on the site automatically. Any requested changes to content on the `master` branch must be related to the released codebase. Any content related to future releases goes in a release integration branch.

See Contribution guidelines (https://github.com/magento/merchdocs/blob/master/.github/CONTRIBUTING.md) and wiki (https://github.com/magento/merchdocs/wiki) for more information.
-->

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by erikmarr** [comment]
@IngusSkaistkalns this content does not look like it belongs in the user guide. @buskamuza can you take a look at this PR to see if this is something we should include in devdocs?

**Comment by IngusSkaistkalns** [comment]
@erikmarr you are right, we can close this PR, but before that please take a minute to read my full story here, maybe that will help to decide where exactly we need to do some improvement in documentation.

Here is the issue:

When you prepare/setup/configure Magento2 instance locally, you will change some various config options, then run app:config:dump to create app/etc/config.php file with all backend settings. This is suggested action from Magento 2.3 devdocs so you can deliver default config on production environment (see deployment pipeline docs). What documentation does not state clear is that those options present in config.php will be locked in backend. 

So when I deployed production version, endusers where telling me they can not change language in backoffice. I had no clue why does this happen and at that moment I was taking a look only at store locale options, I found out that if you remove settings from config.php you again can change settings in backend. I lost(ok, let me be more positive - I invested) some hours figuring that out, so I decided to improve documentation related to my story.

Now I see that this is more related to workflow of configuration and deployment of Magento2, but the issue in my opinion still remains - there is not enough information why something is locked in backoffice, and newbies will have quite a struggle figuring all this out by themselves. They will go to specific Locale change documentation and won't understand why all the dropdown fields are disabled, there is no explanation of why it is like that.

**Comment by shrielenee** [comment]
Hey @IngusSkaistkalns - Thanks for the backstory! If you feel this requires an issue (or a PR) please create one! At this time we will be closing this issue.

**Pull request closed without merging**
