### PR TITLE
Update to actual version of the supported email clients 

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

This pull request (PR) updates supported email clients  for the macOS and Windows10  according to the actual versions

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/marketing/email-clients-supported.html

## Links to source 

- https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439
- -https://support.microsoft.com/en-us/office/set-up-email-in-the-mail-app-for-windows-10-7ff79e8b-439b-4b47-8ff9-3f9a33166c60
- https://www.howto-outlook.com/faq/windows10upgrade.htm#:~:text=Officially%2C%20only%20Outlook%202013%2C%20Outlook,to%20run%20on%20Windows%2010.&text=Continuing%20to%20use%20Outlook%202010,are%20out%20of%20extended%20support.

### CODE REVIEW

**Comment by leslietilling** [comment]
Let's simply remove this page -- it is something old from long ago.

**Comment by keharper** [comment]
Also, add the following text at the bottom of `marketing/email-templates.md`.

"Magento emails can be rendered by HTML and plain text email clients. There might be some variation between clients in the way email are rendered."

**Comment by EvheniiaKolkhiieva** [comment]
Hi @leslietilling and @keharper, thank you for reviewing!

I have implemented the suggestions you describe, could you please review and approve this PR?

Thank you 😊

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
