### PR TITLE
[DOKU] Update documentation regarding Magento2 issue #25674

### PR DESCRIPTION
**Pull request by mautz-et-tong**
## Purpose of this pull request

This pull request (PR) updates the documentation regarding the elasticsearch version notation.

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/catalog/search-elasticsearch.html
- https://docs.magento.com/m2/ce/user_guide/configuration/catalog/catalog.html

## Affected Magento editions

- [ x] Open Source
- [ x] Commerce
- [ x] B2B

## Links to Magento source code or PRs

- https://github.com/magento/magento2/pull/25838)

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by larsroettig** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
Thank you @mautz-et-tong for your submission and thank you @larsroettig for your help to review.

**Pull request merged**
