### PR TITLE
Replacing outdated image for Catalog Images and Video topic

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

This pull request (PR) replaces outdated image for Catalog Images and Video topic

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/catalog/catalog-images-video.html

### CODE REVIEW

**Review by shrielenee — APPROVED** [review]

**Comment by EvheniiaKolkhiieva** [comment]
Thank you @shrielenee for reviewing!

**Comment by shrielenee** [comment]
@magento import pr to magento-devdocs/devdocs

**Comment by magento-engcom-team** [comment]
@shrielenee, an error occurred during the Pull Request import.

**Comment by shrielenee** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@shrielenee the pull request successfully imported.

**Pull request merged**
