### PR TITLE
Update rake preview tasks to use local config

### LINKED ISSUE #111: Speed up local building by providing option to disable link checker
# New feature request

## Description

Hi there! As a feature/dev request for doc authors, I think it would be nice to provide an option to the `rake preview` task (and its subtasks) and be able to disable the link checking on each incremental Jekyll build. Currently the link checking takes the longest, and for me locally when building just one version of the docs (e.g. the CE docs), takes about a minute to build. A majority of this time seems to be spent on checking the validity of links.

## Expected result

While link checking is super useful, when I'm in content-authoring mode, I don't really care about the links, I care more about a tight feedback loop between authoring content, saving it, having Jekyll rebuild, and seeing the result in my browser locally.

Then, before I push up my changes to a branch to start a pull request and kick off a review, I could run the `preview` task with link checking to make sure I didn't introduce any broken links.

## Benefits

Content authors can iterate more quickly when writing documentation locally.

## Possible solutions

Perhaps adding a flag or option to the `rake` tasks? Would a CLI flag like `--no-link-check` or `--disable-link-check` be an option?

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request updates rake tasks (`preview:ce`, `preview:ee`, `preview:b2b`) and the html-checking hook to enable use of local configuration file `_config.local.yml` that is ignored by git. When the file exists, its configuration overrides the default configuration parameters automatically.

For example to disable local link checking, add to the `_config.local.yml`:

```
check_links: false
```

Fixes #111

### CODE REVIEW

**Comment by leslietilling** [comment]
I checked out the branch and ran rake preview. I do not have a `_config.local.yml` file. The command fails:

```
Clean!
Generating devdocs locally ... 
Generating preview of the Open Source edition...
The site will auto-launch in your browser when complete.
bin/jekyll serve --incremental --open-url --trace --plugins=_plugins,_checks --config _config.yml,_config.ce.yml
jekyll 4.0.0 | Error:  Whoops, we can't understand your command.
jekyll 4.0.0 | Error:  invalid option: --config _config.yml,_config.ce.yml
jekyll 4.0.0 | Error:  Run your command again with the --help switch to see available options.
rake aborted!
Command failed with status (1): [bin/jekyll serve --incremental --open-url ...]
/Git/magento/merchdocs/rakelib/preview.rake:46:in `serve'
/Git/magento/merchdocs/rakelib/preview.rake:41:in `preview'
/Git/magento/merchdocs/rakelib/preview.rake:17:in `block (2 levels) in <top (required)>'
/Git/magento/merchdocs/Rakefile:26:in `block in <top (required)>'
Tasks: TOP => preview:all => preview:ce
(See full trace by running task with --trace)
leslies-mbp-2:merchdocs tilling$ 
```

**Comment by dshevtsov** [comment]
@leslietilling thank you for testing the update.
The bug should be fixed now.

**Comment by leslietilling** [comment]
Tested without a `_config.local.yml` file and build works. Also created the local file, set the `check_links: false`, and tested incremental. Updates the changed file without link checking. Looks good :)

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
Created #134 to fix the tests

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
