### PR TITLE
Update security-scan.md

### PR DESCRIPTION
**Pull request by smiverma**
## Purpose of this pull request

We have added a new feature to Magento scan tool that enables merchants to submit PWA stores for scanning through Magento Scan Tool. This feature will be released with the Mid-quarter release on June 22. This pull request describes changes merchants need to make in Venia home page to submit the PWA store for scanning

## Magento release version

This does not affect any Magento version, its only for Magento scan tool

## Product editions

Is this update specific to a product edition?
Both
- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

-https://docs.magento.com/user-guide/magento/security-scan.html

## Additional information

whatsnew
Updated [Security Scan](https://docs.magento.com/user-guide/magento/security-scan.html) for a new feature added to the Magento Scan Tool that that enables merchants to submit PWA stores for scanning.

### CODE REVIEW

**Comment by smiverma** [comment]
@leslietilling can you please review this pull request. Please let me know if you need anything

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@leslietilling the pull request successfully imported.

**Pull request merged**
