### PR TITLE
Update ups.md. Corrected link redirection

### PR DESCRIPTION
**Pull request by denish-c-vachhani**
Sales configuration - shipping origin address options redirect to https://docs.magento.com/m2/ee/user_guide/configuration/sales/shipping-methods.html which is wrong as per given screenshot.

Corrected redirection to >> https://docs.magento.com/m2/ee/user_guide/configuration/sales/shipping-settings.html

## Purpose of this pull request

This pull request (PR) Minor change for redirection.

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/shipping/ups.html

## Affected Magento editions

- [ ] Open Source
- [x] Commerce
- [ ] B2B

## Additional information

image

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
