### PR TITLE
Add new topic about the Dotdigital form

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request adds new topic about the Dotdigital form

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

New topic page link - /user-guide/cms/dotdigital-form.html

### CODE REVIEW

**Review by leslietilling — CHANGES_REQUESTED** [review]
This is already documented by dotdigital here: https://support.dotdigital.com/hc/en-gb/articles/360015568200-Embed-Engagement-Cloud-pages-and-forms-on-your-storefront-Magento-2.

We are in the process of reviewing content related to to vendor-developed extensions and seek to link to their documentation instead of adding to our set so that they can have the ownership of keeping it updated according to their changes and additions.

The form option is listed in https://docs.magento.com/user-guide/cms/page-builder-add-content.html, and links to https://docs.magento.com/user-guide/marketing/dotdigital/engagement-cloud.html. As an alternative to adding aa new topic that duplicates their information, let's add this dotdigital article to the list on that page instead.

**Comment by ZhovnirMaria** [comment]
Hi, @leslietilling 
Did you mean it, did I understand you correctly? Thanks ☺️

**Review by leslietilling — APPROVED** [review]
Yes, thanks @ZhovnirMaria. This is exactly what I meant.

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth the Pull Request is successfully imported.

**Pull request merged**
