### PR TITLE
OM-739: Add OMS Connector to System Reports topic

### PR DESCRIPTION
**Pull request by shrielenee**
## Purpose of this pull request

This pull request (PR) adds an OMS Connector line item to the Available system reports section of the System Reports topic.

Companion PR for OMS Docs: https://github.com/magento-mcom/oms-documentation-en/pull/492

If Magento Commerce, please specify:

Not sure, @JacobBrownAustin can you confirm?

- [x] Commerce only?
- [ ] Commerce with B2B?

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/system/support-system-report.html

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by leslietilling** [comment]
Let's confirm w/ Jacob if this is a Commerce only feature before we merge. If so, it will need to condition this new table row.

**Comment by shrielenee** [comment]
> Let's confirm w/ Jacob if this is a Commerce only feature before we merge. If so, it will need to condition this new table row.

Yeah I'm unfamiliar with using those, so y'all will likely need to assist.

**Comment by shrielenee** [comment]
@JacobBrownAustin Please review question in this PR. Thanks.

**Comment by leslietilling** [comment]
I just looked at the whole topic file (not just the changed lines) and the page is already conditioned for Commerce only (`conditions: Default.EE-B2B` in the front matter). So that pretty much answers our question and this PR can be merged.

**Comment by shrielenee** [comment]
running tests

**Pull request merged**
