### PR TITLE
Root categories cannot be set per store view

### PR DESCRIPTION
**Pull request by mzeis**
## Purpose of this pull request

This pull request (PR) will fix the suggestion that you could set the root category on a store view level. This is only possible on the store (group) level.

## Affected documentation pages

- https://docs.magento.com/m2/ce/user_guide/catalog/category-root.html
- https://docs.magento.com/m2/ee/user_guide/catalog/category-root.html
- https://docs.magento.com/m2/b2b/user_guide/catalog/category-root.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
@mzeis  The file change does not appear to have any modified text. Please review to make sure this is the change that you intended.

**Comment by mzeis** [comment]
@leslietilling Hi, there is a change at the very end of the paragraph. I removed ", and views" because root categories cannot be set per store view.

**Comment by leslietilling** [comment]
Thanks.... GitHub did not mark that but I see it now.

**Comment by ccondra** [comment]
running tests

**Pull request merged**
