### PR TITLE
Added missed option to browser capabilities page

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
## Purpose of this pull request

Added missed option to browser capabilities page

## Affected documentation pages

https://docs.magento.com/user-guide/stores/security-browser-capabilities-detection.html

### CODE REVIEW

**Comment by dobooth** [comment]
Thanks for this, Dmitry. Can you please remove the images from this PR? Thanks.

**Comment by DmitryTsymbal** [comment]
Thanks @dobooth ! The images were removed. Thanks!

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by m2-github-services** [comment]
@dobooth an error occurred during the Pull Request import.

**Comment by DmitryTsymbal** [comment]
Closing this one and opening https://github.com/magento/merchdocs/pull/1689 to avoid an errors during the import.
Thanks!

**Pull request closed without merging**
