### PR TITLE
minor changes to a typo.

### PR DESCRIPTION
**Pull request by aachauhan**
## Purpose of this pull request

This pull request (PR) fixes a minor typo.

If Magento Commerce, please specify:

- [ ] Commerce only?
- [ ] Commerce with B2B?

## Affected documentation pages

- ...
- ...

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by aachauhan** [comment]
Fixed a minor typo

**Comment by leslietilling** [comment]
@aachauhan Thanks for the fix! We cannot process your PR until you sign the Adobe CLA: http://opensource.adobe.com/cla.html

**Comment by ccondra** [comment]
running tests

**Comment by ccondra** [comment]
Thank you!

**Comment by shrielenee** [comment]
@aachauhan When you submit a PR or an issue please completely fill out the provided template. This is mandatory.

**Comment by shrielenee** [comment]
Hey @aachauhan --- You must also sign the CLA for us to process this. Please take care of that and then we'll merge!

**Comment by hickskenh** [comment]
Closing this PR due to non-response from the submitter to sign the required CLA.  change made and submitted in PR 579

**Pull request closed without merging**
