### PR TITLE
Update inventory-about-sources-stocks.md

### PR DESCRIPTION
**Pull request by rrebisz**
## Purpose of this pull request

This pull request (PR) ...

## Affected documentation pages

- ...
- ...

## Affected Magento editions

- [ ] Open Source
- [ ] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/merchdocs?pullRequest=43) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/merchdocs?pullRequest=43) before we can accept your contribution.<br/>

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
You must sign the Adobe CLA before we can process this PR.

**Comment by rrebisz** [comment]
> You must sign the Adobe CLA before we can process this PR.

Done

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
Merging this change. But next time please fill out the PR form with the Purpose and affected pages as a minimum.

**Pull request merged**
