### PR TITLE
Update the list of the Actions Control grid page

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request updates the list of the Actions Control grid page.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/stores/admin-actions-control.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=User%20Content

### CODE REVIEW

**Comment by erikmarr** [comment]
@magento give me 2.4.0 instance

**Comment by erikmarr** [comment]
@magento give me 2.4.0 instance with edition b2b

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
