### PR TITLE
Fix misleading name of menu item to select

### PR DESCRIPTION
**Pull request by chris-pook**
## Purpose of this pull request

This pull request (PR) ...

## Affected documentation pages

- ...
- ...

## Affected Magento editions

- [ ] Open Source
- [ ] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
Please sign the Adobe CLA and provide information (Purpose and Affected topics, others are optional) so that we can process this PR.

**Comment by hickskenh** [comment]
@chris-pook Hey Chris.  Thank you for your contribution.  If you're not aware, we recently opened merchdocs for public submissions and have implemented some new processes and procedures to help establish and maintain consistency.  This process is new for us also.  Please sign the Adobe CLA and provide information for the PR in the template provided (Purpose and Affected topics are required, but others are optional). Once you do those things, we can process this PR quickly. It is a simple but important change, and we thank you for taking the time to submit the correction.

**Comment by hickskenh** [comment]
@chris-pook Hey Chris. We are legally unable to approve and merge a PR without a signed CLA and a completed PR form. If we don't hear from you by Friday, November 8, we'll close your PR. You will lose your points for the submission.

**Comment by hickskenh** [comment]
closing due to inactivity

**Pull request closed without merging**
