### PR TITLE
Update permissions-role-resources.md

### PR DESCRIPTION
**Pull request by hellotaran**
## Purpose of this pull request

This pull request (PR) for #135 

## Affected documentation pages

https://docs.magento.com/m2/ee/user_guide/system/permissions-role-resources.html
- ...

## Affected Magento editions

- [ ] Open Source
- [x] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Comment by leslietilling** [comment]
running tests

**Pull request merged**
