### PR TITLE
Add SuperLinter

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR):
- Checks as much of the source code as possible with linters
- Adds [SuperLinter](https://github.com/github/super-linter) with disabled HTML, XML, and Markdown linting
- Sets the linter to use same triggers as existing _Markdown linting test_
- Sets the linter to run only on new or edited files
- Adds custom configurations for Ruby and Markdown
- Fixes style in the Ruby and Markdown files
- Remains the file with Markdown rules reserved for future use (after the bug is fixed) and adds a symlink at the root of project for IDEs that support [markdownlint](https://github.com/DavidAnson/markdownlint#related).

Also, sets Markdown linting test to use `mdl` of the latest version.

## Additional information

The project does not contain pure HTML and pure XML code at source code. It's been mixed with YAML Liquid. That is why these formats were excluded from validation.

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]
Looks good.

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Comment by dshevtsov** [comment]
running tests

**Pull request merged**
