### PR TITLE
update new section list in change log

### PR DESCRIPTION
**Pull request by hickskenh**
## Purpose of this pull request

This pull request (PR) updates the Changelog to correct the name for ASC 4.0+ (per the TOC) and to add the Amazon Sales Channel 2.x / 3.x section. This specifies that there are separate sections by version.

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/magento/change-log.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

### CODE REVIEW

**Comment by leslietilling** [comment]
The Amazon Sales Channel 2.x/3.x is not new content, so I think adding it as a new section is misleading.

**Comment by hickskenh** [comment]
it is not new content, but it is a new section header.  and i think it is important to let users know there are 2 separate sections by pointing out the old section has been renamed.

**Comment by leslietilling** [comment]
Maybe add a note item under the new section listing that describes the renaming of the exisiting section(with existing content) published alongside the new one. But definitely not listed as a brand new section/set of topics.

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
