### PR TITLE
Fix Broken link

### PR DESCRIPTION
**Pull request by nuzil**
## Purpose of this pull request

Fix Broken link to intallation guide

## Affected documentation pages

https://docs.magento.com/user-guide/magento/installation.html

### CODE REVIEW

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1097`.

**Comment by dobooth** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1097`.

**Comment by dobooth** [comment]
This was merged internally but was not auto-closed.

**Pull request closed without merging**
