### PR TITLE
Fix broken 'Security' and 'Advanced' items on the Configuration Reference page

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

_Describe the goal and the type of changes this pull request covers. Tell us what changes you are making and why._

This pull request (PR) fixes broken 'Security' and 'Advanced' items on the Configuration Reference page
image
image

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Product editions

_Is this update specific to a product edition: Magento Open Source only, Adobe Commerce only?_

- no

_Is this update specific to an installed feature extension: B2B extension, other feature set (please, specify)?_

- no

## Affected documentation pages

_List HTML links for affected pages on <https://docs.magento.com/user-guide/>._

- https://docs.magento.com/user-guide/stores/configuration.html

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]
Thanks for the fix! I think we thought the HTML links would be supported. But the whole thing links, so probably not really needed anyway.

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by EvheniiaKolkhiieva** [comment]
It was the easiest way to fix the problem anyway 😊
Thank you!

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@leslietilling the pull request successfully imported.

**Pull request merged**
