### PR TITLE
Fix incorrect git url for Windows installation

### PR DESCRIPTION
**Pull request by rafal-kos**
## Purpose of this pull request

This pull request (PR) fixs incorrect git clone url for Windows installation

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
Hey @rafal-kos.  Thank you for correcting our error.  As soon as you complete the Adobe CLA agreement, i can approve and merge your PR.  Please [sign the Adobe CLA](https://opensource.adobe.com/cla.html).

**Comment by rafal-kos** [comment]
@hickskenh CLA signed

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
