### PR TITLE
Update customer-groups.md

### PR DESCRIPTION
**Pull request by taoufiqaitali**
## Purpose of this pull request

This pull request (PR) ...

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/customers/customer-groups.html
- https://docs.magento.com/user-guide/v2.3/customers/customer-groups.html

## Links to Magento source code or PRs

- https://github.com/magento/merchdocs/blob/2.4.2-develop/src/customers/customer-groups.md

### CODE REVIEW

**Comment by leslietilling** [comment]
@taoufiqaitali  Is there a code PR that we can reference for this doc update?

**Comment by leslietilling** [comment]
This should merge to master rather than the 2.4.2 develop branch.

**Comment by taoufiqaitali** [comment]
> This should merge to master rather than the 2.4.2 develop branch.

ok done changed base branch to master

**Comment by leslietilling** [comment]
> > This should merge to master rather than the 2.4.2 develop branch.
> 
> ok done changed base branch to master

I tried that and it looks like you branched off of 2.4.2-develop and it is carrying those changes with it. We can't publish them until that release (January). Could you cherry-pick your commit to another branch off of master and resubmit PR?

**Comment by taoufiqaitali** [comment]
@leslietilling ok done PR created #849 
we can close this one

**Pull request closed without merging**
