### PR TITLE
Additional info for Cron configuration settings.

### LINKED ISSUE #222: Feedback on page: /system/cron.html
The current documentation just lists each option which is not very helpful as they can be seen in the actual UI. Please provide a description of each configuration option and it's impact; for those options that are duration based the unit of measure would be very helpful.

### PR DESCRIPTION
**Pull request by karyna-tsymbal-atwix**
## Purpose of this pull request
This PR adds description for Cron configuration settings.

## Affected documentation pages

https://docs.magento.com/m2/ce/user_guide/system/cron.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

## Additional information

Fixes #222

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
Hey @karyna-tsymbal-atwix. Thank you for submitting this update.  I changed the bullet format to a table format and reworded the text to more closely align with definitions in other topics.  Do you mind reviewing and letting me know if you are ok with my changes?

**Comment by karyna-tsymbal-atwix** [comment]
Thank you for the improvement @hickskenh , looks good!

**Comment by hickskenh** [comment]
@karyna-tsymbal-atwix.  That was fast.  Thanks. I'll get it processed and merged.

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
