### PR TITLE
Magento account 2fa

### PR DESCRIPTION
**Pull request by ernestwaynewong**
## Purpose of this pull request

This pull request (PR) contains markdown and related image assets for a new Merchant User Guide page containing detailed instructions for enabling, using, managing, and disabling 2-factor authentication on Magento.com accounts.

If Magento Commerce, please specify:

- [ ] Commerce only?
- [ ] Commerce with B2B?
- [x] All

Note: Magento.com accounts are independent of all Magento products and product versions i.e. these instructions are applicable and relevant regardless of the Magento product or version.

## Affected documentation pages

n/a (this PR is for a new page under https://docs.magento.com/user-guide/magento/magento-account.html)

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by ernestwaynewong** [comment]
Closing PR to fix markdown issues and retry Adobe CLA check.

**Comment by ernestwaynewong** [comment]
Closing PR to fix remaining trailing spaces issues and re-attempt Adobe CLA check.

**Comment by ernestwaynewong** [comment]
Closing PR to fix trailing whitespace issue.

**Comment by leslietilling** [comment]
running tests

**Pull request merged**
