### PR TITLE
Update account-company-update.md

### PR DESCRIPTION
**Pull request by lbortolotto-jakala**
Corrected a typo

## Purpose of this pull request

This pull request (PR) ...

## Affected documentation pages

- ...
- ...

## Affected Magento editions

- [ ] Open Source
- [ ] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
We recently changed to the Adobe CLA in this repo. Please click "Details" and sign so we can process this PR.

**Comment by hickskenh** [comment]
@lbortolotto-jakala Thank you for your contribution. If you're not aware, we recently opened merchdocs for public submissions and have implemented some new processes and procedures to help establish and maintain consistency. This process is new for us also. Please sign the Adobe CLA and provide information for the PR in the template provided (Purpose and Affected topics are required, but others are optional). Once you do those things, we can process this PR quickly. It is a simple but important change, and we thank you for taking the time to submit the correction.

**Comment by hickskenh** [comment]
@lbortolotto-jakala Your PR has been approved, but we are legally unable to merge without a signed CLA and a completed PR form.  If we don't hear from you by Monday, October 28, we'll close your PR and make your change in an internal PR. You will lose your points for the submission.

**Comment by hickskenh** [comment]
Since no reply was received and the required legal requirements are not met, closing this PR.

**Pull request closed without merging**
