### PR TITLE
Convert HTML tables - shipping folder

### PR DESCRIPTION
**Pull request by krisdante**
## Purpose of this pull request

https://github.com/magento/merchdocs/issues/25
Convert tables form HTML format to markdown.

## Affected documentation pages

https://docs.magento.com/m2/ce/user_guide/shipping/magento-shipping-shipment-workflow.html
http://0.0.0.0:4000/m2/ce/user_guide/shipping/shipping-label-package.html
http://0.0.0.0:4000/m2/ce/user_guide/shipping/shipping-label-configure.html

## Affected Magento editions

- [ x ] Open Source
- [ x ] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- ...
- ...

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by jeff-matthews** [comment]
This is a clever approach to simplifying the complex nested HTML tables that we have. 

While at MLEU Contribution Day, @krisdante proposed using definition lists, which I think works well. It deviates from the pattern we use for more simple field reference topics, but I couldn't find examples in the `src/configuration/` directory (as advised in the issue description) that seemed applicable here.

**Comment by hickskenh** [comment]
@krisdante Thank you for your contribution. I have made some changes to your files to remain consistent with the tables and files that have already been converted.  We've been using table formatting for field descriptions and instead of using nesting, we've been using the <br/> command and formatting options manually. It is not the best solution, but it helps maintain consistency with previous setup and presentation.   Please review the changes i made and output.  Let us know if you have questions or other suggestions.

**Comment by hickskenh** [comment]
@krisdante Hey Kris.  I'm going to merge this PR. If you have questions or comments about the changes I made, hit me up in the [slack channel](https://magentocommeng.slack.com/messages/CJP33CEKY). Thanks again for your contribution.

**Pull request merged**
