### PR TITLE
Update pages-core.md

### PR DESCRIPTION
**Pull request by hellotaran**
Remove quotes from page titles #35

## Purpose of this pull request

This pull request (PR) is to fix many instances where the reference to a page is included in quotes, like "Privacy Policy" page.

Removed quote from all the instances.

## Affected documentation pages

https://docs.magento.com/m2/ce/user_guide/cms/pages-core.html

## Affected Magento editions

- [x] Open Source
- [x] Commerce
- [x] B2B

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by leslietilling** [comment]
You must sign the Adobe CLA before we can process this PR. Click the Details link to review and sign.

**Comment by hellotaran** [comment]
Reopening after signing in the CLA.

**Comment by hellotaran** [comment]
> 
> 
> You must sign the Adobe CLA before we can process this PR. Click the Details link to review and sign.

Thank you Leslie.

**Comment by leslietilling** [comment]
running tests

**Pull request merged**
