### PR TITLE
Amazon 4.4 Updates

### PR DESCRIPTION
**Pull request by hickskenh**
## Purpose of this pull request

This pull request (PR) updates the Configuration/Sales Channels/Global Settings topic and images to add "real-only mode" for Amazon 4.4.0.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [ ] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [x] Other feature set, please specify: Amazon Sales Channel

## Affected documentation pages

- https://docs.magento.com/user-guide/configuration/sales-channels.html

whatsnew
Updated the Sales Channels [Global Settings](https://docs.magento.com/user-guide/configuration/sales-channels.html) topic to include the _Read Only Mode_ function.

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]
Looks like you have to sign the SLA. I had to do it a few months back.

**Comment by hickskenh** [comment]
running tests

**Comment by dshevtsov** [comment]
@hickskenh, note that this PR has to be backported to the 2.3-production branch since the change is applicable for 2.3 version.

**Comment by hickskenh** [comment]
Let me double check before answering

Ken Hicks  |  Senior Technical Writer  |  Adobe  |  ***@***.***

From: Dmitry Shevtsov ***@***.***>
Reply-To: magento/merchdocs ***@***.***>
Date: Thursday, March 18, 2021 at 9:44 AM
To: magento/merchdocs ***@***.***>
Cc: Ken Hicks ***@***.***>, Mention ***@***.***>
Subject: Re: [magento/merchdocs] Amazon 4.4 Updates (#1086)


@hickskenh<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhickskenh&data=04%7C01%7Chicks%40adobe.com%7Cc2263b51199948daa9b108d8ea1c5315%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637516754666705263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xbYK8DRwQsZsZVPsWur1JkIgW9zXA6IQmTOTQ%2BCxnV0%3D&reserved=0>, note that this PR has to be backported to the 2.3-production branch since the change is applicable for 2.3 version.

**Comment by leslietilling** [comment]
I will backport along with other tagged PRs.

**Pull request merged**
