### PR TITLE
magento/merchdocs | Fix typos

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
## Purpose of this pull request

Fix pull request fixes https://github.com/magento/merchdocs/issues/1055

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

- https://docs.magento.com/user-guide/marketing/google-tag-manager.html

### CODE REVIEW

**Comment by EvheniiaKolkhiieva** [comment]
Changes were made earlier.

**Comment by dobooth** [comment]
Hi @EvheniiaKolkhiieva Can you please fix the merge conflict here?

**Review by dobooth — CHANGES_REQUESTED** [review]
This PR as written does not fix the Issue. It only adds an unnecessary blank line. Please fix the text and remove the blank line. Such a simple PR should not require change requests.

**Review by dobooth — APPROVED** [review]

**Comment by dobooth** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@dobooth the pull request successfully imported.

**Pull request merged**
