### PR TITLE
Remove b2b and ee labels from the Catalog pages

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request removes b2b and ee labels from the Catalog pages

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [x] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [x] B2B extension
- [x] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/catalog/catalog-menu.html
https://docs.magento.com/user-guide/catalog/product-workspace.html

### CODE REVIEW

**Review by keharper — APPROVED** [review]

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by keharper** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@keharper the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1356`.

**Pull request merged**
