### PR TITLE
Improves instructions on how to create VM attributes

### PR DESCRIPTION
**Pull request by diazwatson**
One of my colleagues had problems creating an attribute to be used in visual merchandiser after following the instructions in this page.
When only realised what was wrong when we look at the source code vendor/magento/module-visual-merchandiser/Model/Config/Source/AllowedAttributes.php:60 and discovered `multiselect` cannot be used for this purpose

## Purpose of this pull request

This pull request (PR) will improves instructions on how to create VM attributes

## Affected documentation pages

- https://docs.magento.com/m2/ee/user_guide/catalog/category-product-rules.html

## Affected Magento editions

- [ ] Open Source
- [x] Commerce
- [ ] B2B

## Links to Magento source code or PRs

- vendor/magento/module-visual-merchandiser/Model/Config/Source/AllowedAttributes.php:60

### CODE REVIEW

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by devops-devdocs** [comment]
An admin must run tests on this PR before it can be merged.

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Comment by hickskenh** [comment]
running tests

**Pull request merged**
