### PR TITLE
Update the "Configure the default pages" block

### PR DESCRIPTION
**Pull request by ZhovnirMaria**
## Purpose of this pull request

This pull request updates the "Configure the default pages" block with more accurate description of the field.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Product editions

Is this update specific to a product edition?

- [ ] Magento Open Source only
- [x] Magento Commerce only

Is this update specific to an installed feature extension

- [ ] B2B extension
- [ ] Other feature set, please specify:

## Affected documentation pages

https://docs.magento.com/user-guide/cms/pages-default.html

### CODE REVIEW

**Review by danidelcar — APPROVED** [review]

**Comment by danidelcar** [comment]
Hi @ZhovnirMaria I see lint check failing due to:

pages-default.md:25: MD009 Trailing spaces. Might have a trailing space in line 25, or line 26 as well.

**Comment by danidelcar** [comment]
> Hi @ZhovnirMaria I see lint check failing due to:
> 
> pages-default.md:25: MD009 Trailing spaces. Might have a trailing space in line 25, or line 26 as well.

Nevermind, I see you fix issue now, great!, thanks!

**Comment by danidelcar** [comment]
@magento import code to magento-devdocs/merchdocs

**Comment by ZhovnirMaria** [comment]
@danidelcar 
Hi, yes there was a trailing space in line 25. I have fixed it.
Thank you, for your support 😊

**Comment by magento-engcom-team** [comment]
@danidelcar the branch with code successfully imported into`magento-devdocs/merchdocs` repository. Branch name: `imported-magento-merchdocs-1245`.

**Pull request merged**
