### PR TITLE
2.3.x - Update installation.md 

### PR DESCRIPTION
**Pull request by antonioavmelo**
Documentation only: text was saying Magento 2.4.x instead of Magento 2.3.x

## Purpose of this pull request

Fix doc. It was strange saying Magento 2.4.x when this page (and all the links) are about Magento 2.3.x

This pull request (PR) ...

## Magento release version

- [X] 2.3.x

## Product editions

Is this update specific to a product edition?

- [X] Magento Open Source only

### CODE REVIEW

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
@antonioavmelo Please sign the Adobe CLA so that we can process this PR: http://opensource.adobe.com/cla.html

**Comment by antonioavmelo** [comment]
Signed Adobe CLA
Regards,
António Melo

**Comment by leslietilling** [comment]
@antonioavmelo  Looks like the system is not recognizing the signature. Please make sure it is tied to your GitHub account.

**Comment by antonioavmelo** [comment]
Hi

I've re-done the process all again. Please check images below. Is the
problem related with my push request having been done before my CLA
signing. I just signed when you asked me, and now again.


Regards,
António Melo

  e-mail: ***@***.***

**Review by leslietilling — APPROVED** [review]

**Comment by leslietilling** [comment]
@magento import pr to magento-devdocs/merchdocs

**Comment by magento-engcom-team** [comment]
@leslietilling the pull request successfully imported.

**Pull request merged**
